version: '3.5'
services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"      
    restart: "always"
    networks:
      - natsbridge

networks:
    natsbridge:
      name: nats-lan
      driver: bridge

